<div id="sequra_partpayment_teaser"></div>
<script type="text/x-magento-init">
    {
        "#sequra_partpayment_teaser": {
            "Sequra_Core/js/widget-js": {
                "css_price_selector": "<?php echo addslashes($block->getData('price_sel'));?>",
                "css_dest_selector": "<?php echo addslashes($block->getData('dest_sel'));?>",
                "product": "pp3",
                "theme": "<?php echo addslashes($block->getData('theme'));?>",
                "sequra_configuration":{
                    "merchant": "<?php echo $block->getMerchantRef(); ?>",
                    "assetKey": "<?php echo $block->getAssetsKey(); ?>",
                    "products": ["i1","pp3","pp5"],
                    "scriptUri": "<?php echo $block->getScriptUri(); ?>",
                    "decimalSeparator": "<?php echo $block->getDecimalSeparator(); ?>",
                    "thousandSeparator": "<?php echo $block->getThousandsSeparator(); ?>",
                    "rebranding": true
                }
            }
        }
    }
</script>
